### ISSUE TITLE
img2img

### ISSUE THREAD

**Issue by randomuser531** [tin2tin/Pallaidium#111]
console tells me for every image model that img2img is not supported - i.e. Flux
is that a shortcomming of the model(s) or not implemented, or result of no controlnet for the bigger xl models? i saw a example of yours where it worked using canny, although it was a older version.
Would really appreciate it working - good work overall!!

**Comment by tin2tin** [comment]
Img2img should work for SDXL(all special features like LoRA etc., are for SDXL)

Flux, being very new FLUX is in process of getting all/most of the features of ex. SDXL. A lot of people are working on this. Pallaidium is using the Diffusers python lib, and they're working on implementing img2img for Flux as we speak: https://github.com/huggingface/diffusers/pull/9070
Once that is committed, I can try to implement it in Pallaidium.

**Comment by randomuser531** [comment]
thats what i thought too, but trying the sdxl ones the console said the same for some reason - i am in the process of setting up pallaidium on a second machine, will come back with learnings..

**Comment by randomuser531** [comment]
just a heads up for a windowsmachine, win11, amd 12cores, 64gb ram, 4070ti 16gb it installs fine - however img2img came back with aura_sr + triton not available, installed aura_sr fine through "Python Module Manager" - triton still missing,as python module manager cannot find a lib that is called triton.

A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\BlenderLauncher\stable\blender-4.2.0-stable.a51f293548ad\4.2\python\Lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
    ^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'triton'
Load: img2img/vid2img Model
Conversion Model:  Vargol/PixArt-Sigma_16bit
The Vargol/PixArt-Sigma_16bit model does not work for a image to image pipeline!
Processing finished.

**Comment by randomuser531** [comment]
img2img works with
juggernaut X Hyper

**Comment by randomuser531** [comment]
aura_sr seems not to work for upscaling, even after "Python module manager" which installed it fine

Error: Python: Traceback (most recent call last):
  File "C:\Users\--\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Pallaidium-main\__init__.py", line 5936, in execute
    sequencer.generate_image()
  File "C:\BlenderLauncher\stable\blender-4.2.0-stable.a51f293548ad\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'aura_sr'
Location: C:\BlenderLauncher\stable\blender-4.2.0-stable.a51f293548ad\4.2\scripts\modules\bpy\ops.py:109


tell me to stop if i am spamming known iss

**Comment by tin2tin** [comment]
The xformers look for triton even though it is not supported on the Win platform - which then causes that message. Triton is not going to be supported on Win and I didn't do Xformers. So, we'll have to live with that message, the rendering works fine even so. The installation of Aura SR lib should be fixed now.

**Comment by tin2tin** [comment]
img2img for Flux is still pending - here: https://github.com/huggingface/diffusers/pull/9135

**Comment by tin2tin** [comment]
@randomuser531 Pallaidium has been updated:
2024-9-14: Add: Flux Inpaint & Img2img.
