### ISSUE TITLE
"Dependencies needs to be installed in the add-on preferences."

### ISSUE THREAD

**Issue by Mikerhinos** [tin2tin/Pallaidium#112]
I followed the readme but every time I try to use it, I have this error "Dependencies needs to be installed in the add-on preferences."

Everytime I click on "install dependencies" it installs it, and at the end when I close the terminal it closes Blender too, and when I restart it I have to "install dependencies" again and again and it never works :(

I just downloaded Blender 4.2.1 LTS, Windows 10.

**Comment by tin2tin** [comment]
Did you right-click on the Blender icon and run as admin as mentioned in the Installation Instructions? If you don't do this, Windows will not allow to actually save the files. 

When do you get that error? If it is when trying to run a model (ex. SDXL)? If it is what model are you trying to use?

**Comment by Mikerhinos** [comment]
Yes I tried both with and without admin rights.
This error is when I try to generate an image using Flux Dev.
When I try to generate a video using Cog I get : 

Python: Traceback (most recent call last):
  File "C:\Users\Mikerhinos\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Pallaidium-main\__init__.py", line 2195, in execute
    import torch
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\torch\__init__.py", line 562, in <module>
    for name in dir(_C):
                    ^^
NameError: name '_C' is not defined

**Comment by tin2tin** [comment]
> there are still dependencies that get installed if I relaunch Blender again in admin and click the "install dependencies" button
Yes, some things are installed everytime you click on Install Dependencies like .whl files. 

> The weird thing is that I see some permission error on some installs, like Torch, and I'm in admin mode
That is properly the issue, and the reason why Torch doesn't install correctly. 

> every steps of the install are in admin mode ?
Yes, I updated the installation instructions with this info. Thank you. 

In general, installation of Torch is very error-prone. If something with Torch goes haywire like in your case I search my harddisk for any folder called something with "orch" in the title, delete it and reboot my computer, before Install Dependencies. The reason for this is that the pip installation procedure can install and look for python libs multiple places on your hdd if you have multiple apps using python. And when uninstalling python libs, pip renames them to ex. ~orch and will use this next time you ask for installing Torch, even if you do not want that version. I should properly look into running Pallaidium in a virtual environment instead, hoping that weird things like this will go away. 

Let me know if any of this solves your problem. BTW. what is your gfx card?

**Comment by Mikerhinos** [comment]
Ok once back from work I'll reinstall Blender and the addon from scratch after cleaning up my dependencies folder, if it's not in a Python venv and using my system Python I probably have a ton of ~ type folders as before using Pinokio I had multiple AIs installed.

My system is Intel i5, 32GB RAM and a 16GB VRAM RTX 4070Ti Super

**Comment by tin2tin** [comment]
@Mikerhinos Let me know if you make any progress?

**Comment by Mikerhinos** [comment]
> @Mikerhinos Let me know if you make any progress?

Oh sorry I made a message but I was doing other things in the same time so it looks like I didn't posted it before turning computer off and going to bed lol.

I tried to reinstall all from scratch, I deleted the ~ folders, reinstalled using the updated readme steps, and when I try to generate a Cog video (or Zero123) I still have a "install libraries" error message. I think that when installing I see some permission errors and version incompatibilities (I don't understand why the permission errors as I'm in admin).

Yes a venv would be cool though it could be a lot of work if I'm the only one with this problem.

**Comment by tin2tin** [comment]
Strange. To work around these permission problems, maybe it'll work for you if you grab a daily version of Blender, unzip it and move it into the documents folder. Could there be any reason for this very restrictive setup on your computer?

https://builder.blender.org/download/daily/

**Comment by Mikerhinos** [comment]
Unfortunately it's the same.
Here is the permission error (which is super weird because it's a permission on this freshly copied nightly, there's no reason I don't have permission on any folder inside it, + why do I already have a ~ folder in it, I deleted every ~ folder in my system's Python :( ):

ERROR: Could not install packages due to an OSError: [WinError 5] Accès refusé: 'C:\\Program Files\\Blender Foundation\\blender-4.3.0-alpha+main.b019e4235ad5-windows.amd64-release\\4.3\\python\\lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

And I also have a bunch of these warnings along the install (plus some errors of incompatible packages versions) :

  WARNING: The script pygmentize.exe is installed in 'C:\Program Files\Blender Foundation\blender-4.3.0-alpha+main.b019e4235ad5-windows.amd64-release\4.3\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by tin2tin** [comment]
Have you tried to uninstall all blender versions (and you could also uninstall python, if that is installed), Automatic1111, Fooookus, anything which could include torch. And then download Blender's daily(link above), unzip into the documents folder (that should be free of restrictions). Open the blender folder right click on the blender.exe. Run as Administrator. And the rest of the installation instructions?

**Comment by Mikerhinos** [comment]
No sorry I'm giving up, problem is on my side and I don't really have time and motivation to track the source.
I'm closing the issue, but thanks for your effort on trying to help me :)

**Comment by tin2tin** [comment]
I'm sorry. Someone at the Discord wanted to help out easing on the windows restrictions. So maybe there will be some changes in that area.

**Comment by Mikerhinos** [comment]
> I'm sorry. Someone at the Discord wanted to help out easing on the windows restrictions. So maybe there will be some changes in that area.

No problem.
Yes for now I'm trying Cog through ComfyUI but VRAM consumption is around 16.3GB and I have 16.0GB available so it's damn slow, around 90s/it :| 
So I'll keep an eye on Pallaidium :)
