### ISSUE TITLE
python torch error? 

### ISSUE THREAD

**Issue by nntb** [tin2tin/Pallaidium#113]
installed git 
followed the install guide on the main page. 
went to video sequincer 
clicked Generative AI 
added a prompt, added a style, set to video and cogvideo clicked generate.... 

Python: Traceback (most recent call last):
  File "C:\Users\nntb\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Pallaidium-main\__init__.py", line 2217, in execute
    clear_cuda_cache()
  File "C:\Users\nntb\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Pallaidium-main\__init__.py", line 577, in clear_cuda_cache
    if torch.cuda.is_available():
       ^^^^^
NameError: name 'torch' is not defined

**Comment by tin2tin** [comment]
Alternatively, you may have some conflicts with previously installed python libs: https://github.com/tin2tin/Pallaidium/issues/112#issuecomment-2316838198

**Comment by fermat01** [comment]
Hi @nntb 
I think  PyTorch library (torch) is not properly imported or installed in your environment. 

1. Try this by running this script to install PyTorch:

```
import sys
import subprocess

pip_install = [sys.executable, "-m", "pip", "install", "torch"]
subprocess.check_call(pip_install)
```

2. If PyTorch is already installed, make sure it's being imported correctly in the  script. At the top of the "Pallaidium-main_init_.py" file, add the following import statement:

import torch
3. If the error persists, it's possible that your environment  is not finding the installed PyTorch package. In this case, you may need to add the path to your Python site-packages to Blender's Python path. 
You can try this by:

- Locating your Python site-packages directory
- Adding the following lines at the beginning of the "Pallaidium-main_init_.py"

```
import sys
sys.path.append('path/to/your/python/site-packages')
import torch
```

**If you're still encountering erros, you may need to reinstall the Pallaidium , ensuring that all its dependencies are 
properly installed in Blender's Python environment.**

Let's me know if it works.

**Comment by tin2tin** [comment]
@fermat01 Thank you for helping out! I would like to add, that this add-on for Blender can be used to install and list the installed python libs: https://github.com/amb/blender_pip
