### ISSUE TITLE
Stable Audio Open Model Missing settings

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Pallaidium#114]
hi i realised i cant generate specify the lenght and so every time its  generating 2 second lenght srtip and even other important settings are missing i thought like shown in huggingsface page here is the screenshot comparing:

![Stable Audio Open Needed Settings in Pallaidium](https://github.com/user-attachments/assets/540bcf93-d3ea-43aa-a399-5c27e5a47538)

**Comment by tin2tin** [comment]
Now you know how to edit the script. Search for stable audio in the file, and somewhere in the UI code the number of frames is not displayed when stable audio open is selected, and somthing needs to be enabled there (remove #)

Do not have time to code now.

**Comment by tin2tin** [comment]
This line: https://github.com/tin2tin/Pallaidium/blob/286165e2c4089a89d113c3ef606a997871cf76be/__init__.py#L1983

Maybe I've disabled it for some reason, like it's failing when the duration isn't fixed.

**Comment by tin2tin** [comment]
Sorry, it was something else. Fix upcoming.

**Comment by tin2tin** [comment]
Thank you for the report. Fixed in: https://github.com/tin2tin/Pallaidium/commit/b063272cebabb082c7407a7c86028f9f63d1b24f
