### ISSUE TITLE
Audio LDM2 Model problem on Linux

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Pallaidium#116]
hi for audio LDM2 there is no setting to specify the length of the sounds generated: 
![image](https://github.com/user-attachments/assets/34d1e348-7400-40d1-b304-a2565126e87d)

and getting some warning and dunno what they mean: 

Model:  vtrungnhan9/audioldm2-music-zac2023
/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/vuaieo/Desktop/UPBGE_29_8_2024/4.3/python/lib/python3.11/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
Loading pipeline components...: 100%|██████████████████████████████████████████| 11/11 [00:04<00:00,  2.46it/s]
Seed: 646178454
Generate: Audio/music (Zac)
Seed: 689864
100%|████████████████████████████████████████████████████████████████████████| 100/100 [00:06<00:00, 15.32it/s]

**Comment by tin2tin** [comment]
Length fixed in: https://github.com/tin2tin/Pallaidium/commit/0b706272b7758e3b869f2aa0bce85667b2a4b762
