### ISSUE TITLE
I Made A Short Experimental Video with this Tool

### ISSUE THREAD

**Issue by reillydonovan** [tin2tin/Pallaidium#24]
My apologies, I didn't know where to post this / relay it to you.
I just want to thank you for this plugin, I had a ton of fun today putting this short video together using it.
Here is my return:

https://www.youtube.com/watch?v=_V7mIGk2QAg

If you have a place you would prefer to post such results, please let me know.  Cheers~

**Comment by tin2tin** [comment]
Wow, that's an excellent video you have done. I love how it moves between the abstract patterns and more realistic elements. It creates great tension between understanding and feeling. That resolution is super good. Did you do post-processing or do you have a good vfx card, so you can render directly in that resolution? 

Do you use the Menu > Add > Generative AI feature to process the content of Text strips as prompt + the pos/neg prompt? If not, you can let it cook overnight on a variety of prompts. The way you use is to add ex style to the pos prompt. And add the elements to texts in text strips, set the batch nr., then you select all of the text strips, and select Menu > Add > Generative AI. And leave it cooking. 

Thanks for sharing. It means a lot to me to know the add-on is being used. If you want, you're welcome to share this and everything else you do with the add-on on BA: https://blenderartists.org/t/generative-ai-add-on-text-to-video-image-and-audio/1456915/1 and/or the Discussions in this repository.

**Comment by tin2tin** [comment]
I've added your video in the Show & Tell section in Discussions: https://github.com/tin2tin/Pallaidium/discussions/82

Thank you.
