### ISSUE TITLE
triton module not found

### ISSUE THREAD

**Issue by Phoenix1969** [tin2tin/Pallaidium#41]
No triton module found
-happens every run
![t](https://github.com/tin2tin/Generative_AI/assets/18568844/fca222a4-df64-4100-a2cf-a2d59990f98c)

**Comment by tin2tin** [comment]
Try to hit Install Dependencies - a few days ago I found a triton build for windows, which seems to work here. Normally isn't Triton for Windows - and that message can be ignored.

**Comment by tin2tin** [comment]
If your Generative AI add-on isn't up-to-date, then do that first.

**Comment by tin2tin** [comment]
Let me know if this solves your issue. Btw. what is that UI?
