### ISSUE TITLE
Error with IF-I-MI 

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/Pallaidium#43]
AttributeError: 'IFPipeline' object has no attribute 'enable_vae_slicing'

**Comment by tin2tin** [comment]
Okay, thank you. That line should just be removed. I do not have enough VRAM to get Deep Floyd working, so I working blind.

**Comment by tin2tin** [comment]
What line is it refering to?

**Comment by b4zz4** [comment]
It's like the CPU version isn't working on me and if I eat all the GPU check lines, I don't get the VRAM.

I have 24GB

**Comment by tin2tin** [comment]
Can't fix as I do not have the hardware to test it.
