### ISSUE TITLE
Vid2Vid Problems

### ISSUE THREAD

**Issue by Aleon3** [tin2tin/Pallaidium#47]
Hi, First off, thanks for what promises to be a huge leap forward in SD/Blender video workflows!

Unfortunately, I have been unable to get the Vid2Vid feature to function.  I consistently get "CUDA out of memory" errors...   I have tried restarting Blender, clearing the cache... no luck.

Moreover, I also get "vae\diffusion_pytorch_model.safetensors not found"  before loading components... but it seems to depend on which video processor is chosen.

I have tried switching processors from the drop-down and then install dependencies, but still get the same error...

I looked at the memory management documentation but am not sure where to make the edits, (different venvs for SDs & several HDs).  I assume that the site-packages folder cited in the error is correct?  Because when I look at the scripts modules\bpy\ops.py:113.. I don't understand how /where to edit to fix.

I am running an RTX3060, 12GB VRAM on Windows 10.

**Comment by tin2tin** [comment]
The  "CUDA out of memory" errors... are hardware dependant. It simply means that the current settings needs more VRAM, so you'll have to lower then until something starts being generated. These processes are super heavy on the system. For vid2vid the number of frames of the source file determines how many frames are rendered. So, if that is too many frames, you'll get that error all the time, unless you input a shorter file. This add-on can be used to re-render a trimed clip, to a shorter clip: https://github.com/tin2tin/Pallaidium#add-rendered-strips
At some point I'll implement automatic processing of trimmed strips. 

Btw. on my 6 GB of VRAM I'm able to produce some ok quality stuff with 1024x512 images with SDXL and then 768x384x10 Zeroscope XL img2vid or 640x320x17. You should be able to go much higher in the number of frames with your additional 4 GB of VRAM.

**Comment by Aleon3** [comment]
Thanks for the guidance.  I will test out and let you know...  

Also, here is a link you may find interesting:
https://stackoverflow.com/questions/54374935/how-can-i-fix-this-strange-error-runtimeerror-cuda-error-out-of-memory

**Comment by Aleon3** [comment]
I was able to get it working... Very Cool! Thanks.  
Another question, the addon forces model installs to huggingface/hub on C:,  Is there any way to change that to the same destination on D:? (where my data is stored and I have more space for it)

**Comment by tin2tin** [comment]
No, not to my knowledge is it possible to move the model path. And thanks for letting me know you got it working.

**Comment by Aleon3** [comment]
I am still working on finding the "sweetspot" for vid2vid... but so far I can say that as long as the strip stays at 24frames or less it is stable for me.  Looking forward to trying the new model and features that you added.  Keep up the great work!
