### ISSUE TITLE
Linux: I always have a Memory error, no matter which settings i use. 

### ISSUE THREAD

**Issue by Craanky** [tin2tin/Pallaidium#49]
Python: Traceback (most recent call last):
  File "/home/robin/.config/blender/3.6/scripts/addons/Pallaidium-main/__init__.py", line 2335, in execute
    image = pipe(
  File "/home/robin/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/robin/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 861, in __call__
    noise_pred = self.unet(
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/robin/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/robin/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 578, in pre_forward
    module.to(self.execution_device)
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/robin/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 5.79 GiB total capacity; 4.55 GiB already allocated; 12.12 MiB free; 4.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by tin2tin** [comment]
Try rendering fewer frames if it is video or if you output an image try lowering the resolution to ex. 768x384 or 640x320. As it seems you're only missing 14 mb. close any program using VRAM and restart Blender, that might give you the few MB you're missing for your current settings. 

Let me know how it goes.

**Comment by tin2tin** [comment]
How much VRAM do you have? What are your settings in the add-on properties? What are your settings in the sidebar panel? 

Did you follow the installation instructions? Did you get to the installation finished message without errors?

**Comment by Craanky** [comment]
6gb, default, default except changed the resolution to 640x320, I got the installation finished message without errors

**Comment by Craanky** [comment]
![Screenshot from 2023-09-11 16-40-57](https://github.com/tin2tin/Pallaidium/assets/140118512/82404a58-9677-464b-816d-6f57042e4759)

**Comment by Craanky** [comment]
512x256 does also not work and yes i added a prompt
also rendering with the gpu stops working after i try to use the addon

**Comment by Craanky** [comment]
![Screenshot from 2023-09-11 16-53-43](https://github.com/tin2tin/Pallaidium/assets/140118512/a5343b50-5143-4812-8652-9af84dbe746d)

**Comment by tin2tin** [comment]
A wild guess is that it could be bc I'm using an older Nvidia driver: https://www.nvidia.com/download/driverResults.aspx/204474/en-us/ 
The later NVIDIA drives seemed to move rendering to CPU at an earlier VRAM level which caused slowdowns. Maybe they have changed that further in later drivers. What NVIDIA driver are you on?

**Comment by Craanky** [comment]
that was a bad example scene, but it still looks like this with lights (as you can see in the top left its out of memory) i already tried restarting and i have a lot of free space on my ssd. I just tried sd 1.5 and i got no error message but it just put out a black image strip. my nvidia driver version is: 525.125.06

**Comment by tin2tin** [comment]
Hmmm.... seems like nsfw prompts can result in a black screen. Try Google stable diffusion 1.5 black screen. 

What if you try Bark/AudioLDM2 and audio output?

**Comment by Craanky** [comment]
It only clears the vram that it used when i restart blender

**Comment by Craanky** [comment]
also when i click uninstall dependencies it says that the ai models are located at .cache/huggingface/transformers but they are located at .cache/huggingface/hub for me

**Comment by Craanky** [comment]
![Screenshot from 2023-09-11 18-04-49](https://github.com/tin2tin/Pallaidium/assets/140118512/9af0d75a-7df6-4443-9f8f-113471f16ada)

**Comment by Craanky** [comment]
it also dont clears the vram it used (see bottom right)

**Comment by tin2tin** [comment]
Things are getting further and further away from anything I've encountered and have any knowledge about. 

As a last ditch attempt, try to read in the Torch bug report thread for how to uninstall dependencies and remove both dependencies and model folders, restart the computer and try reinstalling everything. 

(You could have older python modules etc. and this way you'll get a clean install)

**Comment by tin2tin** [comment]
> also when i click uninstall dependencies it says that the ai models are located at .cache/huggingface/transformers but they are located at .cache/huggingface/hub for me

Thanks for catching this, I'll correct it to hub.

**Comment by tin2tin** [comment]
> my nvidia driver version is: 525.125.06

Another attempt could be to update this to a driver version around version 531.

**Comment by Craanky** [comment]
> > my nvidia driver version is: 525.125.06
> 
> Another attempt could be to update this to a driver version around version 531.

How do you update your driver on debian 12?

**Comment by Craanky** [comment]
i tried reinstalling btw, still didnt work

**Comment by tin2tin** [comment]
Oh, I'm Windows, I don't know anything about Linux.

**Comment by Craanky** [comment]
Thanks for trying to help still, maybe i should have said earlier that im on linux

**Comment by tin2tin** [comment]
I know that some people https://github.com/tin2tin/Pallaidium/pull/42 have it running on Linux, so if you figure out the Nvidia driver update on your OS, that might solve it?

**Comment by tin2tin** [comment]
Any progress?

**Comment by Craanky** [comment]
> Any progress?

no, i think i already have the latest driver version for linux
