### ISSUE TITLE
basic steps not work

### ISSUE THREAD

**Issue by catafest** [tin2tin/Pallaidium#66]
I installed the addon with the default camera and blender 3D cube and I tried to test with basic: "A dream of a distant galaxy".
I saw the button Dream (Render Result) but is inactive and I have no idea about how to fix it.
Any idea?

**Comment by tin2tin** [comment]
Are you trying to process a 3d scene? If so, here's how to do that:

- The process to add a 3d camera is like this: 
- Make a new scene(or copy it) - as you can't reference cameras in the same scene the video sequence is in.
- Add a camera to that scene, and something in front of it.
- In the video sequence scene, add a scene strip to the scene with the camera.
- Select the camera in the sidebar and ex. transparency if you need that.
- In the Sequencer Preview sidebar, go to Scene Strip Display. Change the view to Rendered.
- Install my Add Rendered Strips add-on(link on main page).
- Select your strip.
- Go to menu: Add > Rendered Strips.
- A movie strip should now be rendered and inserted above the Scene strip.
- If the duration of that strip is short enough to be rendered with vid2vid, then do it. If not, render the new strip.

**Comment by catafest** [comment]
I manage how to deal with these steps, is easier to put them all in one video tutorial.

**Comment by tin2tin** [comment]
As this is not bug related, let's continue in Discussions, if you haven't found a solution yet.
