### ISSUE TITLE
Art: Stained Glass calls graffiti style instead

### ISSUE THREAD

**Issue by djooodj** [tin2tin/Pallaidium#71]
I'm finding that the stained glass Art style is not working correctly.

![stained_glass_graffiti_issue](https://github.com/tin2tin/Pallaidium/assets/146207878/f3a9a533-fd7d-4d21-bdb8-d53d104b3350)

**Comment by tin2tin** [comment]
Yes, there is a bug with the enum entry finding code.

**Comment by tin2tin** [comment]
Should be solved now. Thank you.
