### ISSUE TITLE
xFormers can't load C++/CUDA extensions

### ISSUE THREAD

**Issue by limnetik** [tin2tin/Pallaidium#72]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu118)

I get this message when i try to render with sd xl. I tried all i could. Install, deinstall dependencies, xformers, Pytorch, ect... with no success. Maybe you have an idea?
thanks

**Comment by tin2tin** [comment]
If you're on Windows, the first thing to try is to click the Uninstall Dependencies button, restart Blender as admin, and then click Install Dependencies. 

Let me know how it goes.

**Comment by limnetik** [comment]
Done that numerous times, same thing happens. I did encounter another error concerning torch not cuda enabled (i did not note this one) that was stopping anything from working and reinstalled xformers to solve it. I’m on windows. Deinstalling dependencies and reinstalling did not get rid of the message i mention. It does go tru the render, but it’s really slow, like xformers not working i guess. It looks as if the torch installed dependencies are more recent (2.1) than the needed compiled 2.0.1 version indicated. I tried downgrading torch to 2.0.1, but it’s not fixing anything, obviously i don’t really know what i’m doing really…
So, that’s it for now..

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : tin2tin ***@***.***>
Envoyé : Thursday, October 5, 2023 10:45:39 PM
À : tin2tin/Pallaidium ***@***.***>
Cc : Philippe Léonard ***@***.***>; Author ***@***.***>
Objet : Re: [tin2tin/Pallaidium] xFormers can't load C++/CUDA extensions (Issue #72)


If you're on Windows, the first thing to try is to click the Uninstall Dependencies button, restart Blender as admin, and then click Install Dependencies.

Let me know how it goes.

**Comment by tin2tin** [comment]
Well, welcome in the club of not knowing what you're doing... If it actually renders, that is a super-good thing, however it depends on your amount of VRAM. I'm on 6 GB.  And when you're running out of RAM, newer NVIDIA drivers than 532 will start to move rendering to CPU which will make the rendering really slow, so I downgraded and spend a lot of time trying to find my limits without breaking them.

**Comment by limnetik** [comment]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu118)
    Python  3.10.11 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

here is the whole message that suggest there is a mismatch between the downloaded dependencies and the needed ones that causes the xFormers C++/CUDA extensions not to load. The plugins downloads Pytorch 2.1 and xFormers needs 2.0.1. So that's what i understand. Maybe there is a way to make the plugin download the adapted dependencies? 

Also the dependencies are installed in the main python directories; i read somewhere that installing to the blender python directory could do interesting ''things'' to Blender Python compatibilities...anyway these are some thoughts on my intuitions based on my limited, non programmer side of the things and researches. 

Very interesting plugin, by the way, i love the concept of it.

Thanks

**Comment by limnetik** [comment]
I realise automatic1111 Exhibit the same problem now
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11395

**Comment by tin2tin** [comment]
If you need to specify a specific version of xformers, you can try to do it here: https://github.com/tin2tin/Pallaidium/blob/7138218e0661bf56a432745ded57ebf78e2b3a92/__init__.py#L649C48-L649C48
(As it is, it should just be installing the latest version)

It's the last entry in that xformers line which is called when installing. Or alternatively use the pip add-on mentioned on the main page to remove or install python modules in Blender(just remember to restart Blender, when you have uninstalled something)

The joker here is that one of the python modules Pallaidium is using(like Diffusers) might need a specific version of xformers, and installs that instead. It that is happening you can try to change the xformers version with the above-mentioned add-on.

**Comment by tin2tin** [comment]
They're addressing some issues with xformers vs. cuda in Diffusers(which Pallaidium is depending on): https://github.com/huggingface/diffusers/pull/5349

**Comment by tin2tin** [comment]
The problem seems to be that auto1111 and Pallaidium are not using the same xformers version - but as the Pallaidium add-on is using the version dictated by the Diffusers python module, I can't do anything about this. So, I'm closing this report.
