### ISSUE TITLE
can the add-on share model files with the original software like stable diffusions?

### ISSUE THREAD

**Issue by beetaa** [tin2tin/Pallaidium#73]
I think it's a good way to improve the experience with sharing the existing modle files, wich had been download with stable diffusions, animov, bark, etc. just provide the path info from the add-on configuration.

**Comment by tin2tin** [comment]
Pallaidium is accessing the models through the Diffusers module, which dictates where the models are located(hard-coded). There is a bit on the location in the main page of the add-on:
![image](https://github.com/tin2tin/Pallaidium/assets/1322593/6eba4806-56ab-4961-bb8e-5495336d4ca4)

**Comment by beetaa** [comment]
> Pallaidium is accessing the models through the Diffusers module, which dictates where the models are located(hard-coded). There is a bit on the location in the main page of the add-on:
> ![image](https://github.com/tin2tin/Pallaidium/assets/1322593/6eba4806-56ab-4961-bb8e-5495336d4ca4)

The best solution, thank you, 👍
