### ISSUE TITLE
The system cannot find the specified path: 

### ISSUE THREAD

**Issue by ksy20032003** [tin2tin/Pallaidium#88]
when I want to generate something, at first everything goes well, but then this error appearsTraceback (most recent call last):

  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2503, in execute
    filename = solve_path(clean_filename(prompt + ".wav"))
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 258, in solve_path
    create_folder(dir_path)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 244, in create_folder
    os.makedirs(folderpath)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)

[WinError 3] The system cannot find the specified path: 'C:\\Program Files\\Git\\cmd\\git-gui.exe\\2023-11-29' Error: Python: Traceback (most recent call last) :

**Comment by tin2tin** [comment]
Hmmm... that's a new one I haven't seen before. Did you install Git as described in step #1 in the Installation instructions? https://github.com/tin2tin/Pallaidium#how-to-install

**Comment by ksy20032003** [comment]
yes, that's right, installed it

**Comment by ksy20032003** [comment]
![111111](https://github.com/tin2tin/Pallaidium/assets/152379465/3ce55f71-7fd4-47f2-a28d-a3fbcf176339)
I don’t want to seem very stupid, but initially I couldn’t install Palladium and I specified the path to git in filePath, maybe this was the cause of this error. But thanks to this method, I downloaded the dependencies, but now the generation itself does not work

**Comment by tin2tin** [comment]
Oh, that path is the folder where the generated files are saved.

**Comment by ksy20032003** [comment]
strange, then why, when I put this path there, everything was installed... it turns out funny

**Comment by tin2tin** [comment]
Changing that path shouldn't have any effect in the dependency installation procedure, as the path is only used when generating a file.

**Comment by ksy20032003** [comment]
I now returned everything as it was originally and rebooted the laptop, everything seems to be working, well, at least that’s what it looks like, I keep my fingers crossed!

**Comment by tin2tin** [comment]
Okay. Thank you. If you do something cool with Pallaidium, please share. :-)

Closing this as completed.

**Comment by ksy20032003** [comment]
Thank you so much
