### ISSUE TITLE
Animatediff not working?

### ISSUE THREAD

**Issue by limnetik** [tin2tin/Pallaidium#93]
I have blender 4.0.2 installed on windows11.
version 1.8 Pallaidium
RTX3080Ti 16GB vram
When i select animatefiff for video generation i get an error concerning upscale: 

Model:  guoyww/animatediff-motion-adapter-v1-5-2
The config attributes {'motion_activation_fn': 'geglu', 'motion_attention_bias': False, 'motion_cross_attention_dim': None} were passed to MotionAdapter, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.86it/s]
The config attributes {'center_input_sample': False, 'flip_sin_to_cos': True, 'freq_shift': 0, 'mid_block_type': 'UNetMidBlock2DCrossAttn', 'only_cross_attention': False, 'attention_head_dim': 8, 'dual_cross_attention': False, 'class_embed_type': None, 'addition_embed_type': None, 'num_class_embeds': None, 'upcast_attention': False, 'resnet_time_scale_shift': 'default', 'resnet_skip_time_act': False, 'resnet_out_scale_factor': 1.0, 'time_embedding_type': 'positional', 'time_embedding_dim': None, 'time_embedding_act_fn': None, 'timestep_post_act': None, 'time_cond_proj_dim': None, 'conv_in_kernel': 3, 'conv_out_kernel': 3, 'projection_class_embeddings_input_dim': None, 'class_embeddings_concat': False, 'mid_block_only_cross_attention': None, 'cross_attention_norm': None, 'addition_embed_type_num_heads': 64} were passed to UNetMotionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2196, in execute
    upscale.to(gfx_device)
UnboundLocalError: local variable 'upscale' referenced before assignment
Error: Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2196, in execute
    upscale.to(gfx_device)
UnboundLocalError: local variable 'upscale' referenced before assignment
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 4298, in execute
    sequencer.generate_movie()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2196, in execute
    upscale.to(gfx_device)
UnboundLocalError: local variable 'upscale' referenced before assignment
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109

Error: Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 4298, in execute
    sequencer.generate_movie()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2196, in execute
    upscale.to(gfx_device)
UnboundLocalError: local variable 'upscale' referenced before assignment
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109

BLENDER CONSOLE message
Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Pallaidium-main\__init__.py", line 2196, in execute
    upscale.to(gfx_device)
UnboundLocalError: local variable 'upscale' referenced before assignment

**Comment by tin2tin** [comment]
I got that bug fixed, but I fail to get AnimateDiff to produce anything which is not garbage. If you succeed please share your settings with me.

**Comment by limnetik** [comment]
I did get it to work, but for the moment the results were slow and underwhelming; but i am interested into getting something out of it later.

i noticed you did participate to #Diffusetogether ;) Here are my entries i did before knowing about pallaidium’s existence!
THE COURT (Bright Side mix) by Peter Gabriel - DiffuseTogether Animation Challenge - I/O edition
https://youtu.be/eG3cl-9kRH8

I/O (Dark Side mix) by Peter Gabriel - DiffuseTogether Animation Challenge - I/O edition
https://youtu.be/abcYYRAyUVk
i hope you enjoy them :)

**Comment by tin2tin** [comment]
Since you got it to work, I'll close this.
