### ISSUE TITLE
IDEA: Integration with krita-ai-diffusion

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/Pallaidium#96]
https://github.com/Acly/krita-ai-diffusion/tree/main

**Comment by tin2tin** [comment]
Pallaidium already got Inpaint: https://blenderartists.org/t/pallaidium-genai-in-the-video-sequence-editor/1456915/64?u=tin2tin

**Comment by b4zz4** [comment]
Not only has Inpaint, with multilayer control with different models using ControlNet + Comfy UI

**Comment by tin2tin** [comment]
It's already far too much work to keep this add-on working with pyhon modules constantly changing and new AI models out each week, to take on additional integration work with other tools. In addition to this, is everything ControlNet(for SD 1.5) offers already supported in Pallaidium.
